#ifndef TUPLE_TYPE
#define TUPLE_TYPE TUPLE_INET
#endif

#ifndef IOLOOP_TYPE
#define IOLOOP_TYPE IOLOOP_SELECT
#endif

#ifndef HANDLER_LIFECYCLE 
#define HANDLER_LIFECYCLE PROCESS_THREADPOOL
#endif

#define TUPLE_NODE NULL
#define TUPLE_SERVICE "8888"
